/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Alessandra
 * Created: 29-ago-2016
 */

CREATE TABLE Cliente
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128),
    password VARCHAR(128),
    saldo DOUBLE PRECISION
)

INSERT INTO Cliente (id, username, password, saldo)
VALUES  (default, 'angela1', '11', 20.0),
        (default, 'beatrice2', '22', 50.5),
        (default, 'cecilia3', '33', 32.0);

CREATE TABLE Venditore
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128),
    password VARCHAR(128),
    saldo DOUBLE PRECISION
)

INSERT INTO Venditore (id, username, password, saldo)
VALUES  (default, 'delfina4', '44', 25.0),
        (default, 'elena5', '55', 40.5),
        (default, 'federica6', '66', 10.0);


CREATE TABLE Oggetto
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    descrizione VARCHAR(256),
    url VARCHAR(256),
    pezzi INTEGER,
    prezzo DOUBLE PRECISION,
    idVend INTEGER,
    FOREIGN KEY (idVend) REFERENCES Venditore(id)
)

INSERT INTO Oggetto (id, nome, descrizione, url, pezzi, prezzo, idVend)
VALUES  (default, 'Orecchini Etnci', 'Foto orecchini etnici', 'img/etnici.jpg', 50, 5.5, 1),
        (default, 'Orecchini Minnie', 'Foto orecchini minnie', 'img/minnie.jpg', 20, 2.5, 1),
        (default, 'Orecchini Fiore', 'Foto orecchini fiori', 'img/fiori.jpg', 32, 2.5, 2),
        (default, 'Orecchini Cuori', 'Foto orecchini a forma di cuore', 'img/cuori.jpg', 15, 4.0, 3),
        (default, 'Orecchini Rose', 'Foto orecchini rose', 'img/rose.jpg', 16, 3.5, 3);
       